// GENERATED by scripts/gen-tokens.mjs from design/_ds/retainer-design-system-385d60e9-b91c-4f72-93ee-65e829fcd963/tokens.
// Do not edit by hand. Run `pnpm tokens` after re-importing the design system.

export const palette = {
  dark: {
    "void": "#06080a",
    "deep": "#0b0e11",
    "panel": "#10141a",
    "hairline": "#1e242b",
    "ink": "#eef0f2",
    "dim": "#8b929c",
    "faint": "#4c535c",
    "money": "#5ee0b7",
    "people": "#f2a86b",
    "attention": "#9d8cff",
    "lit": "#ffffff",
    "fault": "#ff7a66"
  },
  light: {
    "void": "#f5f4f1",
    "deep": "#ebe9e4",
    "panel": "#ffffff",
    "hairline": "#dcd9d2",
    "ink": "#121417",
    "dim": "#5c636c",
    "faint": "#a7acb2",
    "money": "#5ee0b7",
    "people": "#b15e1e",
    "attention": "#9d8cff",
    "lit": "#121417",
    "fault": "#ff7a66"
  },
} as const;

export type ColorScheme = keyof typeof palette;
export type ColorToken = keyof (typeof palette)['dark'];

export const type = {
  "display": {
    "family": "sans",
    "fontSize": 48,
    "lineHeight": 52,
    "fontWeight": 700,
    "letterSpacing": -1.44
  },
  "title": {
    "family": "sans",
    "fontSize": 24,
    "lineHeight": 30,
    "fontWeight": 600,
    "letterSpacing": -0.48
  },
  "body": {
    "family": "sans",
    "fontSize": 15,
    "lineHeight": 23,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "ui": {
    "family": "sans",
    "fontSize": 14,
    "lineHeight": 20,
    "fontWeight": 500,
    "letterSpacing": 0
  },
  "caption": {
    "family": "sans",
    "fontSize": 13,
    "lineHeight": 18,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "micro": {
    "family": "mono",
    "fontSize": 11,
    "lineHeight": 14,
    "fontWeight": 500,
    "letterSpacing": 1.54,
    "uppercase": true
  },
  "data": {
    "family": "mono",
    "fontSize": 13,
    "lineHeight": 18,
    "fontWeight": 400,
    "letterSpacing": 0
  },
  "data-lg": {
    "family": "mono",
    "fontSize": 32,
    "lineHeight": 36,
    "fontWeight": 500,
    "letterSpacing": -0.64
  }
} as const;

export type TypeVariant = keyof typeof type;

export const space = {
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 24,
  "6": 32,
  "7": 48,
  "8": 96
} as const;

export const radius = {
  "sm": 6,
  "md": 8,
  "panel": 12,
  "node": 999
} as const;

/** CSS box-shadow strings; React Native's New Architecture accepts these via the `boxShadow` style. */
export const glow = {
  "money": "0 0 24px rgba(94,224,183,0.45)",
  "people": "0 0 24px rgba(242,168,107,0.45)",
  "attention": "0 0 24px rgba(157,140,255,0.45)",
  "lit": "0 0 40px rgba(255,255,255,0.55), 0 0 90px rgba(255,255,255,0.25)",
  "peopleLight": "0 0 24px rgba(177,94,30,0.28)"
} as const;

export const motion = {
  "edge": 500,
  "camera": 700,
  "breathe": 2400,
  "easeCamera": [
    0.22,
    0.61,
    0.36,
    1
  ],
  "easeEdge": [
    0.4,
    0,
    0.2,
    1
  ]
} as const;
