#!/usr/bin/env node
// Generates packages/shared/src/tokens.ts from the Retainer design system CSS
// imported from Claude Design (design/_ds/.../tokens/*.css) plus the light
// theme overrides defined in the People wireframe.
//
//   node scripts/gen-tokens.mjs          write the file
//   node scripts/gen-tokens.mjs --check  exit 1 if the file is out of date

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dsDir = join(root, 'design/_ds');
const [dsName] = readdirSync(dsDir).filter((d) => d.startsWith('retainer-design-system'));
if (!dsName) throw new Error('Design system not found under design/_ds');
const tokensDir = join(dsDir, dsName, 'tokens');
const outFile = join(root, 'packages/shared/src/tokens.ts');

/** Parses `--name:value;` declarations out of a CSS block, stripping comments. */
function parseVars(css) {
  const vars = {};
  const clean = css.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const m of clean.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) vars[m[1]] = m[2].trim();
  return vars;
}

const read = (f) => readFileSync(join(tokensDir, f), 'utf8');
const vars = {
  ...parseVars(read('colors.css')),
  ...parseVars(read('typography.css')),
  ...parseVars(read('spacing.css')),
  ...parseVars(read('radius.css')),
  ...parseVars(read('effects.css')),
  ...parseVars(read('motion.css')),
};

const px = (v) => {
  const n = Number(String(v).replace(/px$/, ''));
  if (Number.isNaN(n)) throw new Error(`Not a px value: ${v}`);
  return n;
};
const ms = (v) => Number(String(v).replace(/ms$/, ''));

// Colours: the raw palette only (semantic aliases are var() references).
const COLOR_KEYS = [
  'void',
  'deep',
  'panel',
  'hairline',
  'ink',
  'dim',
  'faint',
  'money',
  'people',
  'attention',
  'lit',
  'fault',
];
const dark = Object.fromEntries(COLOR_KEYS.map((k) => [k, vars[k]]));

// Light theme lives in the People wireframe's helmet <style>.
const wireframe = readFileSync(join(root, 'design/Retainer People.dc.html'), 'utf8');
const lightBlock = wireframe.match(/\[data-theme="light"\]\{([^}]*)\}/);
if (!lightBlock) throw new Error('Light theme block not found in wireframe');
const lightVars = parseVars(lightBlock[1]);
const light = Object.fromEntries(COLOR_KEYS.map((k) => [k, lightVars[k] ?? dark[k]]));

// Type ramp: font family comes from the --text-<style> shorthand.
const TYPE_KEYS = ['display', 'title', 'body', 'ui', 'caption', 'micro', 'data', 'data-lg'];
const type = {};
for (const k of TYPE_KEYS) {
  const size = px(vars[`${k}-size`]);
  const tracking = vars[`${k}-tracking`];
  const letterSpacing = tracking.endsWith('em')
    ? Number((parseFloat(tracking) * size).toFixed(2))
    : 0;
  type[k] = {
    family: vars[`text-${k}`].includes('--font-mono') ? 'mono' : 'sans',
    fontSize: size,
    lineHeight: px(vars[`${k}-line`]),
    fontWeight: Number(vars[`${k}-weight`]),
    letterSpacing,
    ...(k === 'micro' ? { uppercase: true } : {}),
  };
}

const space = Object.fromEntries([1, 2, 3, 4, 5, 6, 7, 8].map((i) => [i, px(vars[`space-${i}`])]));
const radius = {
  sm: px(vars['radius-sm']),
  md: px(vars['radius-md']),
  panel: px(vars['radius-panel']),
  node: px(vars['radius-node']),
};
const glow = {
  money: vars['glow-money'],
  people: vars['glow-people'],
  attention: vars['glow-attention'],
  lit: vars['glow-lit'],
};
if (lightVars['glow-people']) glow.peopleLight = lightVars['glow-people'];
const bezier = (v) =>
  v
    .match(/cubic-bezier\(([^)]+)\)/)[1]
    .split(',')
    .map(Number);
const motion = {
  edge: ms(vars['duration-edge']),
  camera: ms(vars['duration-camera']),
  breathe: ms(vars['duration-breathe']),
  easeCamera: bezier(vars['ease-camera']),
  easeEdge: bezier(vars['ease-edge']),
};

const json = (o) => JSON.stringify(o, null, 2);
const out = `// GENERATED by scripts/gen-tokens.mjs from design/_ds/${dsName}/tokens.
// Do not edit by hand. Run \`pnpm tokens\` after re-importing the design system.

export const palette = {
  dark: ${json(dark).replace(/\n/g, '\n  ')},
  light: ${json(light).replace(/\n/g, '\n  ')},
} as const;

export type ColorScheme = keyof typeof palette;
export type ColorToken = keyof (typeof palette)['dark'];

export const type = ${json(type)} as const;

export type TypeVariant = keyof typeof type;

export const space = ${json(space)} as const;

export const radius = ${json(radius)} as const;

/** CSS box-shadow strings; React Native's New Architecture accepts these via the \`boxShadow\` style. */
export const glow = ${json(glow)} as const;

export const motion = ${json(motion)} as const;
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(outFile, 'utf8');
  } catch {}
  if (current !== out) {
    console.error('packages/shared/src/tokens.ts is out of date. Run `pnpm tokens`.');
    process.exit(1);
  }
  console.log('tokens.ts is up to date');
} else {
  writeFileSync(outFile, out);
  console.log(`wrote ${outFile}`);
}
